//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnLoan
    {
        public int OnLoanId { get; set; }
        public string ISBN { get; set; }
        public System.DateTime date_issued { get; set; }
        public System.DateTime date_due_for_return { get; set; }
        public Nullable<System.DateTime> date_returned { get; set; }
        public int Books_Id { get; set; }
        public int user_Id { get; set; }
    }
}
